### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by Nunsferatus** [MTrab/danfoss_ally#39] opened 2022-10-04 08:01 UTC
Let me start by saying that I am a complete noob.

I have installed the program according to your set-up instructions and everything seemed to go smoothly. I have followed your instructions to the letter.

I am sure that I am missing something since no device appears in the integration add-on (please see print screen).
![image](https://user-images.githubusercontent.com/83787364/193764975-08f9b2f2-14f7-425b-b250-afa8ca894468.png)

could you please help me?

And now my suggestion.
It would be extremely useful for people like me, completely new to this, to have a guide on how to get everything working including troubleshooting.

Many thanks for your help

**Comment by ulrikmh** [comment] 2022-10-04 20:03
you need to ensure the mail you registre your device on and the one you registre on danfoss developer forum are the same

**Comment by Nunsferatus** [comment] 2022-10-05 06:54
Thank you for your reply.

Both the e-mail and password are the same.

**Comment by ulrikmh** [comment] 2022-10-05 07:19
ok, i had some issues with that, and updated the mail in Danfoss app, then restarted the home assistant, and after restart it worked.

**Comment by Nunsferatus** [comment] 2022-10-05 07:32
It did not work :(

**Comment by MTrab** [comment] 2022-10-05 07:39
Are you willing to share your credentials?
I'd be happy to help - credentials can be sent to github_2022@trab.dk

**Comment by Nunsferatus** [comment] 2022-10-05 09:48
I have sent my credentials. Thanks

**Comment by MTrab** [comment] 2022-10-24 07:25
I will close and lock this issue as it is a duplicate of #36 - so let's keep further messages regarding this issue in the original thread.

**Closed by MTrab** 2022-10-24 07:25 UTC
Labels: documentation, DEVELOPMENT HALTED
